mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.ioomex.oledcodeApp.mybatis.entity

spring:
  application:
    name: nacos-service
  server:
    port: 8080

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public

    gateway:
      routes:
        - id: foo-service-route
          uri: http://localhost:9669/
          predicates:
            - Path=/demo/**
        - id: httpbin-route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /${segment}

    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 9978@wzb